---

- name: Test include_vars in roles
  hosts: localhost

  pre_tasks:
    - name: step 0, pre_task
      command: echo "pre_task"

  roles:
    - example

  tasks:
    - name: step 7, task 1 after role
      command: echo "task 1"

    - name: step 8, include sub-tasks
      include: subtask.yml

    - name: step 11, task 2 after role
      command: echo "task 2"

